### ISSUE TITLE
Allow for custom policy arrays based off Department

### ISSUE THREAD

**Issue by kevinVodi** [setup-your-mac/Setup-Your-Mac#116]
**Is your feature request related to a problem? Please describe.**
No problem, just an enhancement to SYM

**Describe the solution you'd like**
After selecting a department in the Welcome screen, allow for custom policy arrays based off what department was selected.

Example: Design dept would get Adobe Creative Cloud in addition to the standard array, where as HR would get Acrobat DC, PeopleSoft, etc

**Describe alternatives you've considered**

Looking into the suggestions noted here:
https://macadmins.slack.com/archives/C04FRRN3281/p1695644288174689?thread_ts=1695408114.558699&cid=C04FRRN3281

**Additional context**
SYM is great! This is just an enhancement request to the stellar product that is SYM.

**Comment by drtaru** [comment]
This would require an additional dialog to pick a configuration as swiftDialog does not allow dynamic selection lists.

**Comment by GadgetGeekNI** [comment]
This might be the path of less resistance.
Rather than maintaining several department specific configs (Making the code huge), it might be easier to have an optional apps array as suggested below.

https://github.com/dan-snelson/Setup-Your-Mac/issues/64

**Comment by astrugatch** [comment]
Just a thought as a work around rather than a change to the script. If you curl your policy JSON from a web host, could you use the department variable as part of your URL (naming the file based on the department it applies to) so that it curls the appropriate JSON per department?

**Comment by dan-snelson** [comment]
@kevinVodi:

After counseling with other sym-devs, I'm going to close this as "not planned."

As you mentioned in your original post, @drtaru offered [one approach on Slack](https://macadmins.slack.com/archives/C04FRRN3281/p1695644288174689?thread_ts=1695408114.558699&cid=C04FRRN3281).
