### ISSUE TITLE
Enrollment Complete plist/setting

### ISSUE THREAD

**Issue by mattdjerome** [setup-your-mac/Setup-Your-Mac#127]
This is not a problem with SYM but a feature that will make it better when integrating into Jamf/other MDM's. We ran into a problem where we use the Enrollment Complete trigger to launch SYM. When your MDM renews the MDM cert every 2 years, it can trigger another enrollment. 

To remedy this on our end we took 2 measures. The first is to run the script only once at enrollment, we also have a custom plist to state the enrollment is complete into an EA. 

it would be helpful if there was a native SYM component to complete this task.

**Comment by dan-snelson** [comment]
… just leave a trail of [breadcrumbs](https://snelson.us/2023/12/breadcrumbs/) …
