### ISSUE TITLE
Turn off connection test

### ISSUE THREAD

**Issue by Honestpuck** [setup-your-mac/Setup-Your-Mac#130]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

**Is your feature request related to a problem? Please describe.**
It's annoying to not know how to turn off the connection test.

**Describe the solution you'd like**
It would be good to have a global variable `connectionTest` with setting of either `true` or `false`

**Describe alternatives you've considered**
I'm not exactly sure how to kill all the bits

**Additional context**

**Comment by drtaru** [comment]
Hey @Honestpuck 

This may just be a case of the option is way down the script at [line 143](https://github.com/setup-your-mac/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L143C1-L143C73)
`configurationDownloadEstimation="true"      # [ true (default) | false ]`

Setting that to false should prevent the connection testing from occurring.

Please let us know if this is not the behavior you are expecting.

**Comment by Honestpuck** [comment]
Your right. That is indeed the problem. Let's close this.
