### ISSUE TITLE
brandingBannerDisplayText Not Respected

### ISSUE THREAD

**Issue by seaneldridge7** [setup-your-mac/Setup-Your-Mac#139]
> Before submitting a **Setup Your Mac** bug report, please review the [open swiftDialog issues](https://github.com/bartreardon/swiftDialog/issues) to help determine the source of the issue.

**Describe the bug**
Despite having `brandingBannerDisplayText="false"` the text still appears over the top of a custom branding banner.

**To Reproduce**
- Download a fresh copy of the script, add a custom image to line 109 and set line 110 to false. 
 
**Expected behavior**
I wouldn't expect to see anything other than the custom branding bannner 

**Code/log output**
`brandingBanner="/Users/Shared/Resources/Wallpapers/custom.png" 
brandingBannerDisplayText="false"`

**Screenshots**
![image](https://github.com/setup-your-mac/Setup-Your-Mac/assets/160036657/1f8ce0db-c2e5-4a5d-9981-b8d9888f95c1)

**Environment (please complete the following information):**
 - 14.3
 - 1.12.10 & 1.14.0

**Additional context**
This problem manifested itself at the same time as the update to swiftDialog 2.4.1

**Comment by drtaru** [comment]
Hi @seaneldridge7,
Are you using the WelcomeDialog to collect userInput?
If yes, does the banner display correctly there, with no text?

**Comment by seaneldridge7** [comment]
> Hi @seaneldridge7, Are you using the WelcomeDialog to collect userInput? If yes, does the banner display correctly there, with no text?

Hi @drtaru, no we're not using that in our workflow. However, if I take a fresh copy of the script and only modify those two lines with a custom banner and set the text to false, the same problem occurs at the userInput screen. 

![Screenshot 2024-02-14 at 2 26 55 PM](https://github.com/setup-your-mac/Setup-Your-Mac/assets/160036657/bf06068b-a0d5-405c-956d-14901a7a0cbc)

**Comment by drtaru** [comment]
Perfect, thanks, that helps me narrow it down. 
I will dig in!

**Comment by drtaru** [comment]
Found the issue, seems like if `bannerText` is set to nothing `""` then the `title` parameter takes over
The fix is to set `bannerText=" "` instead of `bannerText=""` when `brandingBannerDisplayText="false"`
PR #140 should fix this, you can wait for it to be merged or test the changes yourself now.

**Comment by dan-snelson** [comment]
This should have been closed back in February.
