### ISSUE TITLE
Conditional steps in the JSON policy

### ISSUE THREAD

**Issue by Bearzooka** [setup-your-mac/Setup-Your-Mac#142]
**Is your feature request related to a problem? Please describe.**
On my fleet we don't actively use the **departments** or **buildings** to discern what software and settings a device gets, as this information is provided at a later step.

However, I would like for a certain task to be only executed on devices that will be handed to developers (regardless of their department) which are identifiable by the RAM size (32 or more for Devs, and less than that for the others).

**Describe the solution you'd like**
It would be cool to be able to include a `conditions` section in the JSON file that checks for certain files and decides if the policy needs to be executed (or even shown in the GUI). Then, at an earlier step I could run whatever is necessary and put the files where the condition will expect it.

The logic is not to far from the logic used for the validations, but needs to run once **before** populating the list.

**Describe alternatives you've considered**
For my particular use case I have a policy with different parameters for each case, and then smart groups are scoped accordingly.

**Comment by dan-snelson** [comment]
@Bearzooka:

After counseling with other sym-devs, I'm going to close this as "not planned."

(You may wish to create a Smart Computer Group for computers with more than `32` GB of RAM and scope policies to it.)
