### ISSUE TITLE
JAMF email notification for the individual devices 

### ISSUE THREAD

**Issue by mani2care** [setup-your-mac/Setup-Your-Mac#143]
Looking forward email notification once the enrollment completes and the incase any failure to follow the instructions further steps to install the application instead of slack or trams notification for some case organisation not using that both and mostly using JAMF SMTP protocol for the notification.

**Comment by dan-snelson** [comment]
@mani2care:

After counseling with others, I'm going to close this as "not planned."

The recommended approach is to enable [SMTP Server Integration](https://learn.jamf.com/bundle/jamf-pro-documentation-current/page/SMTP_Server_Integration.html) within Jamf Pro and enable "Send email notification on membership change" for a manually created "SYM Complete" Smart Group. (See: [Breadcrumbs](https://snelson.us/2023/12/breadcrumbs/).)

![Screenshot 2024-02-25 at 8 11 07 AM](https://github.com/setup-your-mac/Setup-Your-Mac/assets/24623109/b7c66355-5b27-4ad3-a2ca-1ea70ff772f6)
