### ISSUE TITLE
EULA feature integration 

### ISSUE THREAD

**Issue by mani2care** [setup-your-mac/Setup-Your-Mac#144]
would like to know SYM is having built in functionality for the end user license agreement page ? Is that possible to integrate its a wonderful feature to have who are using the SYM by manually enrolling the device 

https://github.com/swiftDialog/swiftDialog/issues/328#issuecomment-1885977450

**Comment by azgmacos** [comment]
i recently implemented something similar in my own SYM iteration, please see the following as an example:

`title="CIO Technology Services"
icon="/Library/Application Support/Dialog/Dialog.png"
message="**Please Confirm the EULA to Enroll with $$$$$$$$**  \n\nBy clicking \"I Confirm\", you acknowledge that this device is provided by $$$$$$$$$ and is **NOT** a **PERSONAL** or **CLIENT-OWNED** Mac.  \n\nOnly devices provided by $$$$$$$$ are authorized to enroll into $$$$$$$ Systems.  \n\n**It is against $$$$$$$$$ Policy 57 to enroll non-$$$$$$$$$ Mac devices.**"
button1="Continue"
button2="Cancel"
updateScriptLog "Prompting user to confirm that the device is $$$$$$$$ provided"
userClick=$("$swiftDialog" --icon "$icon" --title "$title" --message "$message" --eula --checkbox "I Confirm this is an $$$$$$$ provided Mac authorized to enroll into $$$$$$$ Systems",enableButton1 --button1disabled --button1text "$button1" --button2text "$button2" --infobox "**Action Required**  \n\nConfirm the EULA:  \n\nEID: ${loggedInUser}  \nDevice: ${serialNumber}" --height 475 --width 550)
userClick=$?
if [[ $userClick == 0 ]]; then
    updateScriptLog "Clicked confirm.. proceeding to enrollment"
elif [[ $userClick == 2 ]]; then
    updateScriptLog "User did not confirm device is $$$$$$$$$ provided, removing from Jamf, removing MDM profiles and Jamf framework"
    sudo /usr/local/jamf/bin/jamf policy -event deleteComputerRecord
    sudo /usr/local/jamf/bin/jamf removemdmprofile
    sudo /usr/local/jamf/bin/jamf removeframework
    exit 1
fi`


the $$$$$ is where i redacted the company name, hope this helps

**Comment by dan-snelson** [comment]
Thanks for the FR, @mani2care.

After counseling with other sym-devs, I'm going to close this as "not planned."

(However, I _think_ someone **might** have an idea for you …)
