### ISSUE TITLE
Add a "table view" option for displaying text in the welcome screen.

### ISSUE THREAD

**Issue by howieisaacks** [setup-your-mac/Setup-Your-Mac#146]
Just after I deployed SYM into production, I needed to make some minor changes to it. One of the changes I needed to make was adding additional support contact information. My company has employees all around the world and we have support teams who are (mostly) local to them. Attached is an example of what I would like to be able to do (easily) in SYM. I did figure out how to make the text display this way but the coding was very rough. I did not like the way I ended up having to do it. I know that Swift Dialog supports using tables. Maybe that would be the solution.  I was fine with just a vertical list but I was asked to make it look this way. Thank you for all of your time working on SYM! You are appreciated.
![support example](https://github.com/setup-your-mac/Setup-Your-Mac/assets/45493689/89a565d4-3b03-4f4e-8913-4cefcefeb519)

**Comment by dan-snelson** [comment]
@howieisaacks:

After counseling with other sym-devs, I'm going to close this as "not planned."

That said, as you mention, swiftDialog supports [tables](https://github.com/swiftDialog/swiftDialog/wiki/Customising-the-Message-area#markdown-support), so you're free to edit the message as you see fit:

<img width="932" alt="Screenshot 2024-05-28 at 3 42 00 PM" src="https://github.com/setup-your-mac/Setup-Your-Mac/assets/24623109/44caf07b-d94c-43cc-8e69-3967ceff330f">

```
dialog --message "| United States Offices |   | International Offices |
|----------------------------------------------------------|---|-------------------------------------------------------|
| USA<br /> Telephone: (801) 555-1212<br /> Email: us@domain.com |   | APAC<br /> Telephone: (801) 555-1212<br /> Email: apac@domain.com |                                                          |   |                                                       |" --infotext
```
