### ISSUE TITLE
Move to site with prompt department

### ISSUE THREAD

**Issue by stondelier** [setup-your-mac/Setup-Your-Mac#147]
Hello 
I'd like to be able to use the prompt given by the “department” user to deploy a different configuration for each option by moving it to the site corresponding to the department.

![image](https://github.com/setup-your-mac/Setup-Your-Mac/assets/51954067/ba019710-011d-48c1-9a75-12d7f425dd27)

example:
REMA --> rules1, rules2, rules4
SIEG --> all rules

Can you please guide me on how to do this?

**Comment by dan-snelson** [comment]
Greetings, @stondelier!

For a faster response, please join us on the [Mac Admins Slack](https://snelson.us/2022/12/setup-your-mac-mac-admins-slack-channel/).

**Comment by dan-snelson** [comment]
@stondelier: I'm going to mark this "closed as completed." Thanks.
