### ISSUE TITLE
Incorrect failure message displayed 

### ISSUE THREAD

**Issue by arnoldtaw** [setup-your-mac/Setup-Your-Mac#149]
**Describe the bug**
Upon detecting a failure, the correct failure message was not displayed. Instead, it displayed the placeholder text. 
`Placeholder message; update in the 'finalise' function`

**To Reproduce**
Unable to reproduce consistently. Correct customized failure message was displayed in most cases. Once in a while, we will get this message. 

**Expected behavior**
Upon detecting a failure, display the correct failure message.

**Code/log output**
N/A

**Screenshots**
![Screenshot 2024-05-07 at 8 26 23 AM](https://github.com/setup-your-mac/Setup-Your-Mac/assets/2093094/97998123-29d4-489f-bcd1-aaa3c6ad1d8b)

**Environment:**
 - macOS 14.4.1
 - Script version 1.14.2
 - swiftDialog 2.4.2

**Comment by jcmbowman** [comment]
I'm consistently running into this bug. Glad it's already been identified. Happy to assist with troubleshooting.

**Comment by jcmbowman** [comment]
Fixed on my end by changing sleep time to 0.7 here:
https://github.com/setup-your-mac/Setup-Your-Mac/blob/084c8293115df89fd9db0343cacb45ec99b01631/Setup-Your-Mac-via-Dialog.bash#L1719

**Comment by dan-snelson** [comment]
@arnoldtaw: While I'm aware of other reports of this unexpected behavior, I'm not able to replicate it.

That said, please advise if [`1.15.0-b7`](https://github.com/setup-your-mac/Setup-Your-Mac/blob/1.15.0/Setup-Your-Mac-via-Dialog.bash#L348) resolves the issue.

Thanks.

**Comment by dan-snelson** [comment]
Addressed in SYM `1.15.0`.
