### ISSUE TITLE
Setup-Your-Mac at LoginWindow

### ISSUE THREAD

**Issue by ayumpo** [setup-your-mac/Setup-Your-Mac#153]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

**Is your feature request related to a problem? 
It is not a problem

**Describe the solution you'd like**
I would like to Launch Setup-Your-Mac at the Jamf Connect Login Screen, now that SwiftDialog 2.5.0 Supports it.

**Additional context**
![image](https://github.com/setup-your-mac/Setup-Your-Mac/assets/77344348/fac74080-1a0d-4029-8fbe-df6fef994b40)

**Comment by dan-snelson** [comment]
Thanks, @ayumpo.

As [discussed on Slack](https://macadmins.slack.com/archives/C04FRRN3281/p1718312172098269), feature-complete Pull Requests are always welcome.

**Comment by ayumpo** [comment]
Hi @robjschroeder, I use your Post-install script for Setup-Your-Mac and it works wonders, but would like to know if is possible to modify it to make it Launch Setup-Your-Mac at the Jamf Connect Login Window instead :D, Thank you.

**Comment by robjschroeder** [comment]
They LD waits for AppleSetupDone before continuing to call your SYM policy in Jamf Pro. This would be the first piece. The second would be to modify SYM to work at the login window, as @dan-snelson says a feature complete PR is definitely welcome!

**Comment by dan-snelson** [comment]
@ayumpo: This feels like a perfect use-case for [Jamf Setup Manager](https://github.com/Jamf-Concepts/Setup-Manager/blob/main/README.md); closing as "not planned."
