### ISSUE TITLE
Dynamic Window Height for Build Dialog

### ISSUE THREAD

**Issue by sjbarkey** [setup-your-mac/Setup-Your-Mac#154]
**Is your feature request related to a problem? Please describe.**
When building a VM in VMware Fusion Pro, the build workflow takes place prior to VMware Tools being installed, which forces the VM to run at 1024x768 resolution. Unfortunately, this means that the button at the bottom of the build dialog when when the deployment completes is off-screen and can not be clicked.

**Describe the solution you'd like**
Dynamically detect the screen resolution prior to the start of the build dialog being displayed and use a lower/higher height value based on the resolution.

**Describe alternatives you've considered**
- I have tried installing VMware Tools via the policy array, but to complete the install and resolve the resolution issue, a reboot is required, which means the issue isn't resolved with the build dialog.
- I have manually set the height value to a lower value for testing and that does result in the build dialog being fully visible. Unfortunately, depending on the policy array size, this could result in a negative user experience when building on a device with a higher resolution.

**Additional context**
I can provide screenshots if that would help.

**Comment by dan-snelson** [comment]
Greetings, @sjbarkey

Search the script for `height` and change to your liking. 

Thanks.

**Comment by sjbarkey** [comment]
@dan-snelson Is it possible to have the script dynamically set the height based on the screen resolution?

**Comment by dan-snelson** [comment]
See [Custom Window Sizes](https://github.com/swiftDialog/swiftDialog/wiki/Window-Size-and-Behaviour#custom-window-sizes)

**Comment by liquidz00** [comment]
@sjbarkey In full transparency, I am not incredibly versed in Swift so there may be a more efficient way of achieving this. For your use cases, you may be able to implement this function into a local clone of SYM on your machine in the event it doesn't make sense to integrate with the full project: 
```swift
import Foundation
import AppKit

func getScreenResolution() -> (width: Int, height: Int) {
        if let mainScreen = NSScreen.main {
            let resolution = mainScreen.frame
            return (Int(resolution.width), Int(resolution.height))
        } else {
            return (0, 0)
        }
    }
```
I tested this on a 14" MBP and a M2 Mac Mini and it returned the proper results.

**Comment by sjbarkey** [comment]
@dan-snelson Thank you!  I'm not sure how I missed that as I have read that section several times and somehow glossed over the percentage option entirely! 🤦‍♂️ 


@liquidz00 Thank you for the script!  I will definitely get it a shot if the percentage option doesn't work for our use case during testing.
