### ISSUE TITLE
Issue with Duplicate Infobox Keys Causing Details to be Invisible in UI

### ISSUE THREAD

**Issue by mani2care** [setup-your-mac/Setup-Your-Mac#155]
here is a duplicate infobox causing the details to be invisible in the UI. When I disable the keys below, the details disappear. After removing the dummy infobox="", it starts working again. Please address this issue.

The details are not visible when I disable the keys at this link:
https://github.com/setup-your-mac/Setup-Your-Mac/blob/b5f268e6b5871c08baeae68e72b802593b8a99fd/Setup-Your-Mac-via-Dialog.bash#L2182

There is a duplicate, and it overlooks the keys above when I disable the keys at this link:
(https://github.com/setup-your-mac/Setup-Your-Mac/blob/b5f268e6b5871c08baeae68e72b802593b8a99fd/Setup-Your-Mac-via-Dialog.bash#L3402)

infobox="**Operating System:** ${macOSproductVersion} (${macOSbuildVersion}) \n\n **Serial Number:** \n ${serialNumber} \n\n **Dialog Version:** \n ${dialogVersion} \n\n **Contact:** \n ${supportTeamEmail} \n\n **KB:** \n ${supportTeamErrorKB} \n\n **Started:** \n ${timestamp}"

I have disabled all of these, and I am unable to view the infobox details. and by removing the L2182 I am able to fix.
```
# [SYM-Helper] These control which user input boxes are added to the first page of Setup Your Mac. If you do not want to ask about a value, set it to any other value
promptForUsername="false"
prefillUsername="false"          # prefills the currently logged in user's username
promptForRealName="false"
prefillRealname="false"          # prefills the currently logged in user's fullname
promptForEmail="false"
prefillEmail="false"             # prefills the currently logged in user's email. You need to add to email ending variable
promptForComputerName="false"
prefillComputerName="false"      # prefills the currently logged in user's current computer name
promptForAssetTag="false"
promptForRoom="false"
promptForBuilding="false"
promptForDepartment="false"
promptForPosition="false"        # When set to true dynamically prompts the user to select from a list of positions or manually enter one at the welcomeDialog, see "positionListRaw" to define the selection / entry type
promptForConfiguration="false"   # Removes the Configuration dropdown entirely and uses the "Catch-all (i.e., used when `welcomeDialog` is set to `video` or `false`)" or presetConfiguration policyJSON

# Set to "true" to suppress the Update Inventory option on policies that are called
suppressReconOnPolicy="true"

# [SYM-Helper] Disables the Blurscreen enabled by default in Production
moveableInProduction="true"

configurationDownloadEstimation="false"   
```

<img width="256" alt="image" src="https://github.com/user-attachments/assets/5357becf-5aee-48c0-9110-0486d0f592c6">

**Comment by dan-snelson** [comment]
Greetings, @mani2care!

Please advise the SYM settings to replicate.

Please also advise the versions of:
- macOS
- swiftDialog
- SYM

**Comment by mani2care** [comment]
Please make it fales all of this below in your SYM and test it out 

# [SYM-Helper] These control which user input boxes are added to the first page of Setup Your Mac. If you do not want to ask about a value, set it to any other value
promptForUsername="false"
prefillUsername="false"          # prefills the currently logged in user's username
promptForRealName="false"
prefillRealname="false"          # prefills the currently logged in user's fullname
promptForEmail="false"
prefillEmail="false"             # prefills the currently logged in user's email. You need to add to email ending variable
promptForComputerName="false"
prefillComputerName="false"      # prefills the currently logged in user's current computer name
promptForAssetTag="false"
promptForRoom="false"
promptForBuilding="false"
promptForDepartment="false"
promptForPosition="false"        # When set to true dynamically prompts the user to select from a list of positions or manually 
promptForConfiguration="false"   # Removes the Configuration dropdown entirely and uses the "Catch-all (i.e., used when 
suppressReconOnPolicy="true"
moveableInProduction="true"
configurationDownloadEstimation="false"   

The details are not visible when I disable the keys at this link:
 infobox="Analyzing input …"
 
 Dialog Version:2.5.0.4768
Operating System:13.6.3 (22G436)
SYM :1.15.0

**Comment by dan-snelson** [comment]
What do settings do you have for the following lines?

https://github.com/setup-your-mac/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L45-L46

**Comment by mani2care** [comment]
Yes i have set it up like below 

debugMode="${5:-"false"}"                                                  
welcomeDialog="${6:-"userInput"}"

and disabled some of below i just want only the message so 

promptForUsername="false"
prefillUsername="false" # prefills the currently logged in user's username
promptForRealName="false"
prefillRealname="false" # prefills the currently logged in user's fullname
promptForEmail="false"
prefillEmail="false" # prefills the currently logged in user's email. You need to add to email ending variable
promptForComputerName="false"
prefillComputerName="false" # prefills the currently logged in user's current computer name
promptForAssetTag="false"
promptForRoom="false"
promptForBuilding="false"
promptForDepartment="false"
promptForPosition="false" # When set to true dynamically prompts the user to select from a list of positions or manually
promptForConfiguration="false" # Removes the Configuration dropdown entirely and uses the "Catch-all (i.e., used when
suppressReconOnPolicy="true"
moveableInProduction="true"
configurationDownloadEstimation="false"

**Comment by mani2care** [comment]
Sorry for the trouble i have correct my self the option i have to set "welcomeDialog="${6:-"messageOnly"}"
thanks @dan-snelson  given the clue.now its working fine as expected.

i have noticed one more trouble is that the welcome heading is not in center 

<img width="771" alt="image" src="https://github.com/user-attachments/assets/244f9120-263e-4d24-84fb-554b6b0674e8">

**Comment by dan-snelson** [comment]
See [Customising the Title](https://github.com/swiftDialog/swiftDialog/wiki/Customising-the-Title).
